### ISSUE TITLE
Problems with any requests

### ISSUE THREAD

**Issue by 3JIou** [karan/TPB#85]
`

**Comment by 3JIou** [comment]
i find problem - old code in pip repo

**Comment by 3JIou** [comment]
some any problem

**Comment by 3JIou** [comment]
`
for torrent in t.top().category(tpb.CATEGORIES.VIDEO.MOVIES):
    print(torrent)

Connected to pydev debugger (build 143.1919)
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 2411, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1802, in run
    launch(file, globals, locals)  # execute the script
  File "/Users/batman/Documents/projects/PycharmProjects/torrent_parser/tpb/tox-test.py", line 8, in <module>
    for torrent in t.top().category(tpb.CATEGORIES.VIDEO.MOVIES):
  File "/usr/local/lib/python2.7/site-packages/tpb/tpb.py", line 62, in items
    self._get_torrent_rows(root)]
  File "/usr/local/lib/python2.7/site-packages/tpb/tpb.py", line 89, in _build_torrent
    [category, sub_category] = [c.text for c in cols[0].findall('.//a')]
ValueError: too many values to unpack
`
./tpb.py
`
         [category, sub_category] = [c.text for c in cols[0].findall('.//a')]
`
need `try`
like this 
`
        try:
            [category, sub_category] = [c.text for c in cols[0].findall('.//a')]
        except ValueError:
            return
`

**Comment by ClayCons** [comment]
@3JIou How did you solved the `urllib2.HTTPError: HTTP Error 403: Forbidden
` issue?

**Comment by adenosinetp10** [comment]
Did you make sure piratebay is not blocked by your ISP in your region ?

**Comment by mattcar15** [comment]
I'm running into the same issue. It isn't blocked in my region

**Comment by adenosinetp10** [comment]
Go through the source code of the API and check if piratebay has shifted to another domain.....

**Comment by mattcar15** [comment]
The urls are quite out of date. This library seems to be kinda abandoned?
